[package]
name = "xlinerpc"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[lints]
workspace = true
